<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-01T07:41:23 MST" name="Default suite" finished-at="2025-04-01T07:41:34 MST" duration-ms="10766">
    <groups>
      <group name="login">
        <method signature="LoginTest.testcase01()[pri:1, instance:testNg_Practice.LoginTest@771a660]" name="testcase01" class="testNg_Practice.LoginTest"/>
        <method signature="LoginTest.testcase02()[pri:2, instance:testNg_Practice.LoginTest@771a660]" name="testcase02" class="testNg_Practice.LoginTest"/>
      </group> <!-- login -->
    </groups>
    <test started-at="2025-04-01T07:41:23 MST" name="Default test" finished-at="2025-04-01T07:41:34 MST" duration-ms="10766">
      <class name="testNg_Practice.LoginTest">
        <test-method is-config="true" signature="buildexecution()[pri:0, instance:testNg_Practice.LoginTest@771a660]" started-at="2025-04-01T07:41:23 MST" name="buildexecution" finished-at="2025-04-01T07:41:26 MST" duration-ms="2473" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildexecution -->
        <test-method signature="testcase01()[pri:1, instance:testNg_Practice.LoginTest@771a660]" started-at="2025-04-01T07:41:26 MST" name="testcase01" description="verify log in functionality with valid values " finished-at="2025-04-01T07:41:26 MST" duration-ms="404" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MainHMRr] but found [MainHMR]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MainHMRr] but found [MainHMR]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at testNg_Practice.LoginTest.testcase01(LoginTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase01 -->
        <test-method is-config="true" signature="buildClose()[pri:0, instance:testNg_Practice.LoginTest@771a660]" started-at="2025-04-01T07:41:26 MST" name="buildClose" finished-at="2025-04-01T07:41:26 MST" duration-ms="173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildClose -->
        <test-method is-config="true" signature="buildexecution()[pri:0, instance:testNg_Practice.LoginTest@771a660]" started-at="2025-04-01T07:41:26 MST" name="buildexecution" finished-at="2025-04-01T07:41:27 MST" duration-ms="1269" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildexecution -->
        <test-method signature="testcase02()[pri:2, instance:testNg_Practice.LoginTest@771a660]" started-at="2025-04-01T07:41:27 MST" name="testcase02" description="verify log in functionality with valid username and invalid password " finished-at="2025-04-01T07:41:34 MST" duration-ms="6394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase02 -->
        <test-method is-config="true" signature="buildClose()[pri:0, instance:testNg_Practice.LoginTest@771a660]" started-at="2025-04-01T07:41:34 MST" name="buildClose" finished-at="2025-04-01T07:41:34 MST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buildClose -->
      </class> <!-- testNg_Practice.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
